#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname $0)/.."

echo "prepare phantomjs for test"
npm rebuild phantomjs-prebuilt

echo "yarn test"
yarn test

echo "yarn build"
yarn build

echo "docker login"
docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

echo "docker build -t ${REPO}:${TAG}"
docker build -t $REPO:$TAG .

echo "docker push ${REPO}:${TAG}"
docker push $REPO:$TAG

if [ "$BRANCH" == "master" ]; then
  echo "docker tag ${REPO}:${TAG} ${REPO}:latest"
  docker tag $REPO:$TAG $REPO:latest

  echo "docker push ${REPO}:latest"
  docker push $REPO:latest
fi
